In [1]:
import numpy as np
np.__version__

'1.26.4'

In [3]:
import pandas as pd
pd.__version__

'2.2.3'

In [5]:
import matplotlib.pyplot as plt
%matplotlib inline

In [7]:
my_data = pd.read_csv('Admission_Predict.csv')

In [9]:
my_data

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0             1        337          118                  4  4.5   4.5  9.65   
1             2        324          107                  4  4.0   4.5  8.87   
2             3        316          104                  3  3.0   3.5  8.00   
3             4        322          110                  3  3.5   2.5  8.67   
4             5        314          103                  2  2.0   3.0  8.21   
..          ...        ...          ...                ...  ...   ...   ...   
395         396        324          110                  3  3.5   3.5  9.04   
396         397        325          107                  3  3.0   3.5  9.11   
397         398        330          116                  4  5.0   4.5  9.45   
398         399        312          103                  3  3.5   4.0  8.78   
399         400        333          117                  4  5.0   4.0  9.66   

    Research  Chance of Admit   
0        Yes              0.92  
1        Yes              0.76  
2        Yes              0.72  
3        Yes              0.80  
4         No              0.65  
..       ...               ...  
395      Yes              0.82  
396      Yes              0.84  
397      Yes              0.91  
398       No              0.67  
399      Yes              0.95  

[400 rows x 9 columns]

In [45]:
x = my_data.iloc[:,1:7].values
y = my_data.iloc[:,-1].values   # it may be 8 row or last first row -1

In [47]:
x

array([[337.  , 118.  ,   4.  ,   4.5 ,   4.5 ,   9.65],
       [324.  , 107.  ,   4.  ,   4.  ,   4.5 ,   8.87],
       [316.  , 104.  ,   3.  ,   3.  ,   3.5 ,   8.  ],
       ...,
       [330.  , 116.  ,   4.  ,   5.  ,   4.5 ,   9.45],
       [312.  , 103.  ,   3.  ,   3.5 ,   4.  ,   8.78],
       [333.  , 117.  ,   4.  ,   5.  ,   4.  ,   9.66]])

In [49]:
y

array([0.92, 0.76, 0.72, 0.8 , 0.65, 0.9 , 0.75, 0.68, 0.5 , 0.45, 0.52,
       0.84, 0.78, 0.62, 0.61, 0.54, 0.66, 0.65, 0.63, 0.62, 0.64, 0.7 ,
       0.94, 0.95, 0.97, 0.94, 0.76, 0.44, 0.46, 0.54, 0.65, 0.74, 0.91,
       0.9 , 0.94, 0.88, 0.64, 0.58, 0.52, 0.48, 0.46, 0.49, 0.53, 0.87,
       0.91, 0.88, 0.86, 0.89, 0.82, 0.78, 0.76, 0.56, 0.78, 0.72, 0.7 ,
       0.64, 0.64, 0.46, 0.36, 0.42, 0.48, 0.47, 0.54, 0.56, 0.52, 0.55,
       0.61, 0.57, 0.68, 0.78, 0.94, 0.96, 0.93, 0.84, 0.74, 0.72, 0.74,
       0.64, 0.44, 0.46, 0.5 , 0.96, 0.92, 0.92, 0.94, 0.76, 0.72, 0.66,
       0.64, 0.74, 0.64, 0.38, 0.34, 0.44, 0.36, 0.42, 0.48, 0.86, 0.9 ,
       0.79, 0.71, 0.64, 0.62, 0.57, 0.74, 0.69, 0.87, 0.91, 0.93, 0.68,
       0.61, 0.69, 0.62, 0.72, 0.59, 0.66, 0.56, 0.45, 0.47, 0.71, 0.94,
       0.94, 0.57, 0.61, 0.57, 0.64, 0.85, 0.78, 0.84, 0.92, 0.96, 0.77,
       0.71, 0.79, 0.89, 0.82, 0.76, 0.71, 0.8 , 0.78, 0.84, 0.9 , 0.92,
       0.97, 0.8 , 0.81, 0.75, 0.83, 0.96, 0.79, 0.

In [51]:
from sklearn.model_selection import train_test_split

In [53]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [55]:
from sklearn.linear_model import LinearRegression

ams = LinearRegression()

In [57]:
type(ams)

sklearn.linear_model._base.LinearRegression

In [59]:
ams.fit(x_train, y_train)

LinearRegression()

In [61]:
YPredict = ams.predict(x_test)

In [63]:
YPredict

array([0.70881817, 0.70262748, 0.77240747, 0.62205053, 0.73582831,
       0.61124487, 0.71714321, 0.65292633, 0.86687357, 0.91801312,
       0.53947817, 0.88424849, 0.72307567, 0.45980778, 0.8514757 ,
       0.63064774, 0.61578864, 0.80827666, 0.59604868, 0.74556705,
       0.87296795, 0.86511492, 0.66517862, 0.45673087, 0.77573973,
       0.58844281, 0.47595716, 0.65215698, 0.88813941, 0.66137422,
       0.62672553, 0.73273382, 0.73159537, 0.55850536, 0.80081569,
       0.76459144, 0.64152744, 0.85705921, 0.63837959, 0.92827437,
       0.71894784, 0.68354549, 0.70124561, 0.80289266, 0.84102657,
       0.66934111, 0.57270212, 0.70323271, 0.61323152, 0.60834018,
       0.68507886, 0.79388635, 0.63782335, 0.87960669, 0.71108315,
       0.74452279, 0.70271517, 0.72841892, 0.77517926, 0.82387567,
       0.78802719, 0.47142621, 0.64771045, 0.52538952, 0.83833109,
       0.81356996, 0.72472789, 0.86324566, 0.78691899, 0.7452375 ,
       0.60832698, 0.82502567, 0.81917112, 0.5917218 , 0.93360

In [65]:
from sklearn.metrics import mean_squared_error, r2_score

In [67]:
mse = mean_squared_error(y_test, YPredict)
r2 = r2_score(y_test, YPredict)

print("Mean Squared Error:", mse)
print("R-squared:", r2)

Mean Squared Error: 0.00490143475948048
R-squared: 0.7302083954878602


In [69]:
comparsion = pd.DataFrame(x_test, columns=["GRE Score","TOEFL Score","University Rating","SOP",	"LOR","CGP"])

In [71]:
comparsion["avl_o/p"] = y_test

In [73]:
comparsion["pre_o/p"] = YPredict

In [75]:
comparsion

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGP  avl_o/p  \
0       309.0        105.0                5.0  3.5  3.5  8.56     0.71   
1       308.0        110.0                4.0  3.5  3.0  8.60     0.70   
2       326.0        110.0                3.0  3.5  3.5  8.76     0.79   
3       306.0        105.0                2.0  3.0  2.5  8.26     0.73   
4       316.0        105.0                3.0  3.0  3.5  8.73     0.72   
..        ...          ...                ...  ...  ...   ...      ...   
75      311.0        104.0                3.0  3.5  2.0  8.20     0.61   
76      306.0        103.0                2.0  2.5  3.0  8.36     0.69   
77      313.0        106.0                2.0  2.5  2.0  8.43     0.62   
78      334.0        116.0                4.0  4.0  3.5  9.54     0.93   
79      297.0         96.0                2.0  2.5  1.5  7.89     0.43   

     pre_o/p  
0   0.708818  
1   0.702627  
2   0.772407  
3   0.622051  
4   0.735828  
..       ...  
75  0.618784  
76  0.644154  
77  0.653718  
78  0.906753  
79  0.514999  

[80 rows x 8 columns]